workflows:
  default-workflow:
    name: Default Workflow
    environment:
      vars:
        AWS_ACCESS_KEY_ID: Encrypted(Z0FBQUFBQmQzYmJ3VGphcGFETy1FcU9qd2ZTX3hfWFRMaDJBUFF0STBZZ0pKNDJyalZvQmhLeWNJYWNvM1NBOG81cldGVnNQdmp4Z0huVjNKMm5HZHlWanZQdkpfdmp0c0pMdUlmMkJEaGtuQ1ZrV3VCc3FBVmM9)
        AWS_SECRET_ACCESS_KEY: Encrypted(Z0FBQUFBQmQzYmJ3cHdHM0dNVzd6WVFLM1ZjZkhHZndVVml2QmxQQmNJWUMzYlpveFA5Z0lpOEoxSll1aXJDa1hGTWFiOF94TWFyczd3ZWMxSGJEd29RWlhxZ1RIR1k4SjN2ZWZ2c0NmWDUtRGVRN0hscmtZUElvT3N6VmJ4aDJFVUVsNW9tNHhPMVM=)
      flutter: dev
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter config --enable-web
      - flutter test
      - flutter build apk --release
      - |
        # build web
        flutter build web --release
        cd build/web
        7z a -r ../web.zip ./*

        cd $FCI_BUILD_DIR/build/
        sudo pip3 install awscli --upgrade
        aws s3 sync web/ s3://flutter-ci-cd-flutter/

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - me@danielschroeder.org
